apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-platform

resources:
  - namespace.yaml
  - api-gateway.yaml
  - new-services.yaml
  - hpa.yaml

commonLabels:
  environment: dev
  managed-by: kustomize
